apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: dis
build:
  artifacts:
  - image: api
    context: packages/api
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/api.yaml
  helm:
    releases:
      - name: postgresql
        setValues:
          volumePermissions.enabled: true
        remoteChart: postgresql-ha
        repo: https://charts.bitnami.com/bitnami
        namespace: dis

      - name: vault
        remoteChart: vault
        namespace: dis
        repo: https://helm.releases.hashicorp.com